package com.example.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * linked-list structure for the CURLOPT_QUOTE option (and other)<br>
 * <i>native declaration : include\curl\curl.h:2385</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class curl_slist extends Structure {
	/** C type : char* */
	public Pointer data;
	/** C type : curl_slist* */
	public curl_slist.ByReference next;
	public curl_slist() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("data", "next");
	}
	/**
	 * @param data C type : char*<br>
	 * @param next C type : curl_slist*
	 */
	public curl_slist(Pointer data, curl_slist.ByReference next) {
		super();
		this.data = data;
		this.next = next;
	}
	public static class ByReference extends curl_slist implements Structure.ByReference {
		
	};
	public static class ByValue extends curl_slist implements Structure.ByValue {
		
	};
}
