package com.example.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : include\curl\curl.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class curl_ssl_backend extends Structure {
	/**
	 * @see curl_sslbackend<br>
	 * C type : curl_sslbackend
	 */
	public int id;
	/** C type : const char* */
	public Pointer name;
	public curl_ssl_backend() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("id", "name");
	}
	/**
	 * @param id @see curl_sslbackend<br>
	 * C type : curl_sslbackend<br>
	 * @param name C type : const char*
	 */
	public curl_ssl_backend(int id, Pointer name) {
		super();
		this.id = id;
		this.name = name;
	}
	public static class ByReference extends curl_ssl_backend implements Structure.ByReference {
		
	};
	public static class ByValue extends curl_ssl_backend implements Structure.ByValue {
		
	};
}
