// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs godefs_ignore.go

package wrapper

type StructDemo struct {
	A   int32
	B   int32
	C   int8
	Str *int8
}
type EnumDemo uint32
type UnionDemo [16]byte

type CURLcode uint32
